### ISSUE TITLE
plex-bloat-fix: Plex is running, exiting

### ISSUE THREAD

**Issue by minuskaos** [bullmoose20/Plex-Stuff#16]
Will this script not run if plex is running? 
I've tried to kill it and it still says it's running. What processes is it checking for? 

```
#######################################################################
# BEGIN:            Ver:1.3.7
#######################################################################
#######################################################################
Log file:           logs/plex-bloat-fix.log created...
DB_PATH VALID:      This is a local run which will COPY the database
WARNING:            At least one of the SQLite temp files is next to the Plex DB; this indicates Plex is still running and the DB cannot be safely copied. If you recently restarted plex as part of this run, you should be fine.
ERROR:              Plex is running, exiting
```

**Comment by minuskaos** [comment]
Still having this issue. I've killed everything I can think of and still getting the same error

**Comment by Flam1ngFir3ball** [comment]
Same issue here, I was able to downgrade from a backup. Version 1.3.5 work fine.

**Comment by minuskaos** [comment]
> Same issue here, I was able to downgrade and version 1.3.5 work fine.
> 
> https://github.com/bullmoose20/Plex-Stuff/blob/98c81e4526f3efc9387f80866f70d227d5dc4034/plex-bloat-fix.py

Thanks, Where can I get the supporting files? I'm still running into a new issue which I'm guessing is related to that




```
$ python plex-bloat-fix.py
Python-dotenv could not parse statement starting at line 10
#######################################################################
# BEGIN             Ver:1.3.5
#######################################################################
# UPGRADE           Current Ver:1.3.5 New Ver:1.3.7
#######################################################################
Log file:           plex-bloat-fix.log created...
DB_PATH VALID:      This is a local run which will COPY the database
Traceback (most recent call last):
  File "C:\Server\Plex-Stuff\plex-bloat-fix.py", line 343, in <module>
    if not Path(DIR_PATH).is_dir():
           ^^^^^^^^^^^^^^
  File "C:\Users\Media Center\AppData\Local\Programs\Python\Python311\Lib\pathlib.py", line 871, in __new__
    self = cls._from_parts(args)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Media Center\AppData\Local\Programs\Python\Python311\Lib\pathlib.py", line 509, in _from_parts
    drv, root, parts = self._parse_args(args)
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Media Center\AppData\Local\Programs\Python\Python311\Lib\pathlib.py", line 493, in _parse_args
    a = os.fspath(a)
        ^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType

```

**Comment by minuskaos** [comment]
Got it working by removing quotes from path on 1.3.5 thanks [Flam1ngFir3ball](https://github.com/Flam1ngFir3ball)

**Comment by chazlarson** [comment]
The "plex is running" error is displayed on local runs if two sqlite temporary files are present next to the plex db file.

These two files, `[database-name].db-shm` and `[database-name].db-wal` are internal sqlite temporary files, and indicate that the database is being held open for writing with [possibly] some changes not yet written to the DB file itself.

If PBF's case, since it's about to make a copy of the DB and do queries against it, this *may* result in recently-uploaded images getting deleted since their paths have not yet made it to the database proper.

The error says "plex is running" since the most likely thing to be holding the plex database open for writing is Plex.

There is a setting you can use to override this warning and continue on with the attendant risk of data loss.

If you set `OVERRIDE_PLEX_RUNNING_WARNING` to True in the env, PBF will sail right past this warning and continue on.  This does carry a risk that a poster you uploaded in the recent past will be erroneously deleted.

**Comment by bullmoose20** [comment]
1.3.8 was released to address the text in the error. Going back to an earlier version of PBF can almost always guarantee that additional files in PLEX will be deleted as a result of changes  that PLEX made recently
